kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ebs-node-privileged-binding
subjects:
  - kind: ServiceAccount
    name: ebs-csi-node-sa
    namespace: openshift-aws-ebs-csi-driver
roleRef:
  kind: ClusterRole
  name: ebs-privileged-role
  apiGroup: rbac.authorization.k8s.io
