apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
  name: aws-ebs-csi-driver-trusted-ca-bundle
  {{ if index . "hyperShiftConfig" }}
  namespace: {{ .hyperShiftConfig.controlPlaneNamespace }}
  {{ else }}
  namespace: openshift-cluster-csi-drivers
  {{ end }}
