apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-ebs-csi-driver-controller-sa
  {{ if index . "hyperShiftConfig" }}
  namespace: {{ .hyperShiftConfig.controlPlaneNamespace }}
  {{ else }}
  namespace: openshift-cluster-csi-drivers
  {{ end }}
