apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: aws-ebs-csi-driver-controller-pdb
  namespace: ${NAMESPACE}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: aws-ebs-csi-driver-controller
