# This image contains scripts and YAML manifests for e2e tests.
# It is going to be used to install the operator in prow jobs
# of all sidecars & AWS EBS CSI driver to prevent regressions.

FROM registry.svc.ci.openshift.org/openshift/origin-v4.0:base
WORKDIR /go/src/github.com/openshift/aws-ebs-csi-driver-operator

# Make a full copy of the operator sources for now to be able
# to experiment in a prow job without changing this image.
# TODO: extract just the files we need for e2e.
COPY . .
