apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: aws-ebs-csi-driver-controller-pdb
  namespace: openshift-cluster-csi-drivers
  labels:
    control-plane: "true"
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: aws-ebs-csi-driver-controller
