apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: ${ASSET_PREFIX}-controller-metrics-serving-cert
  labels:
    app: ${ASSET_PREFIX}-controller-metrics
  name: ${ASSET_PREFIX}-controller-metrics
  namespace: ${NAMESPACE}
spec:
  ports:
  selector:
    app: ${ASSET_PREFIX}-controller
  sessionAffinity: None
  type: ClusterIP
